#!/bin/bash

GAME_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
source "$GAME_DIR/lib/typewriter-regular.sh"

typewriter ""
typewriter "    Together Jill and Barry passed through the double doors"
typewriter "    and entered a long, extravagant dining room. The storm"
typewriter "    picked up outside. The air smelled.. of…"
typewriter ""
typewriter "        Barry: What? What is this? . . .Blood?"
typewriter "          . . .Hope this is not Chris's blood..."
typewriter ""
typewriter "    Jill stood behind Barry who squatted down examining the"
typewriter "    puddle of blood in front of him. Before Jill could do"
typewriter "    anything, a door in the far corner creaked open. . ."
typewriter ""
typewriter "        Jill: Who is that?"
typewriter ""
typewriter "    A man shambled out from under the large dining table."
typewriter "    He raised his arms, covered in blood, and groaned"
typewriter "    approaching Jill and Barry."
typewriter ""
typewriter "        Barry: Hey, you, stop!"
typewriter ""
typewriter "    The man didn't listen, only limped closer."
typewriter "    His eyes completely cloudy, as if he were already dead."
typewriter "    Behind him, Jill pointed to a body partially under the"
typewriter "    table. . ."
typewriter ""
typewriter "    It was Kenneth, from S.T.A.R.S. Bravo Team. . ."
typewriter "    his throat ripped out."
typewriter ""
typewriter "        Barry: He's insane!"
typewriter ""
typewriter "    Barry fired his Colt .45."
typewriter "    The man . . . er, Zombie took one more step forward."
typewriter "    Then their head popped like a balloon."
typewriter ""
typewriter "        Barry: What the hell?"
typewriter "        Jill: Let's report this to Wesker!"
typewriter ""


# Unhide the doors after the scene
mv "$(dirname "$0")/../.browndoor" "$(dirname "$0")/../browndoor"
mv "$(dirname "$0")/../.bluedoor" "$(dirname "$0")/../bluedoor"
