#!/bin/bash

GAME_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$GAME_DIR/lib/typewriter-regular.sh"

typewriter ""
typewriter "    Jill read the name of the directory, Cultivation_Room, on the"
typewriter "    blast door. Entering the password, the blast door lifted up."
typewriter ""
typewriter "    Somewhere inside, someone was typing on a keyboard."
typewriter ""
typewriter "    Jill and Barry stepped inside. The blast door locked behind them."
typewriter "    The air was cold, and a thin fog collected around their boots."
typewriter "    Jill took a step forward, watching her wonky reflection move in"
typewriter "    all the large foggy glass tubes that filled the room."
typewriter "    Through them, she saw him."
typewriter ""
typewriter "        Jill: Wesker?"
typewriter ""
typewriter "        Wesker: Well, well..."
typewriter ""
typewriter "    Wesker didn't even turn around to look at them. Just kept"
typewriter "    typing on the keyboard."
typewriter ""
typewriter "        Barry: Cut the crap, Wesker."
typewriter "          We read the orders.txt..."
typewriter ""
typewriter "        Jill: Why do you have to destroy S.T.A.R.S.?"
typewriter ""
typewriter "        Wesker: That's Umbrella's intention. This laboratory has been"
typewriter "          engaging in dangerous experiments, and recently, an"
typewriter "          accident occurred. A virus got out. Anyway, this disaster"
typewriter "          cannot be made public."
typewriter ""
typewriter "        Jill: Is that why having S.T.A.R.S. nosing about is so"
typewriter "          inconvenient? You're a slave to Umbrella, along with"
typewriter "          these virus monsters."
typewriter ""
typewriter "        Wesker: I think you misunderstand me, Jill. I'm going to"
typewriter "          burn this entire laboratory. If you helped create one"
typewriter "          of the most powerful biological weapons. . ."
typewriter "          what would you do?"
typewriter ""
typewriter "        Jill: You must stop this now."
typewriter ""
typewriter "        Wesker: Hmph. Idiots, no one understands its real value."
typewriter ""
typewriter "        Jill: So you're going to steal all the research?"
typewriter ""
 typewriter "       Wesker: Better yet. I'm going to show you the Tyrant."
typewriter ""
typewriter "    Wesker stopped typing on the keyboard. To his left, one of the"
typewriter "    large tubes started to drain. An ungodly creation inside."
typewriter "    Over 8 feet tall, with a giant mutated claw as its left hand,"
typewriter "    and a giant beating heart exposed on the chest."
typewriter ""
typewriter "    The Tyrant opened its eyes."
typewriter ""
typewriter "        Wesker: The Tyrant is the most powerful biological weapon"
typewriter "          in the entire world. All this power will be mine. . ."
typewriter ""
typewriter "    In one swift motion, the Tyrant broke through the glass with"
typewriter "    its mutated hand."
typewriter ""
typewriter "        Wesker: What? Don't come this way!"
typewriter ""
typewriter "    In one second, the Tyrant was out of the test tube and lifting"
typewriter "    Wesker to his feet. The next, the mutated claw pierced through"
typewriter "    his chest."
typewriter ""
typewriter "        Barry: Jill..."
typewriter ""
typewriter "    Barry placed a hand on Jill. Slowly encouraging her to step back"
typewriter "    quietly before... The Tyrant turned, seeing them. Nowhere to run."
typewriter ""
typewriter "    The Tyrant threw Wesker's body across the room into a panel of"
typewriter "    computer devices. Then the towering monster bared its oversized"
typewriter "    teeth at them."
typewriter ""
typewriter "        Jill: Barry, fire!"
typewriter ""
typewriter "    Both S.T.A.R.S. members aimed, and fired everything into the"
typewriter "    Tyrant's exposed beating heart. Barry's Colt .45 knocked the"
typewriter "    Tyrant off its feet."
typewriter ""
typewriter "          [Overhead: THIS FACILITY WILL DETONATE. ALL DOORS ARE NOW UNLOCKED.]"
typewriter "    			[Overhead: ALL PERSONNEL MUST EVACUATE IMMEDIATELY...]"
typewriter ""
typewriter "    Around them, emergency lights flashed. A loud siren blared on repeat."
typewriter ""
typewriter "        Barry: Jill we have to escape!"
typewriter ""

# create .self-destruct-sequence.sh to play whenever entering a directory
# create .gamestat Enter_Cultivation_Room.sh=true
#   this will remove passwords from: /Holding_Cells and ./Emergency_Helipad
