#!/bin/bash
GAME_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$GAME_DIR/lib/typewriter-regular.sh"

typewriter ""
typewriter "    Wesker: Wow, what a mansion!"
typewriter ""
typewriter "  They stood on a lush red rug that went from the large"
typewriter "  front doors all the way up the grand staircase. Marble"
typewriter "  floors caught bright flashes of thunder outside, booming"
typewriter "  all around them in the large main hall."
typewriter ""
typewriter "    Jill: Captain Wesker, where's Chris?"
typewriter "    Wesker: Stop it! Don't open that door!"
typewriter "    Jill: But Chris is--"
typewriter ""
typewriter "  ...might be out there, Jill was saying but a gun went off"
typewriter "  somewhere in the mansion, to the left, behind some"
typewriter "  DoubleDoors."
typewriter ""	
typewriter "    Barry: What is it?"
typewriter "    Wesker: Maybe it's... Chris... Jill--Can you go?"
typewriter ""
typewriter "    Barry: I'm going with you."
typewriter "        Chris is our old partner, ya know."
typewriter ""
typewriter "    Wesker: Stay alert!"
typewriter ""
typewriter "  Jill was relieved Barry was coming with her."
typewriter "  And that he was bringing his Colt .45 with him."
typewriter ""
typewriter "    Barry: Remember those commands that got us in here?"
typewriter "      Use them to change directory to doubledoors
typewriter ""
