#!/bin/bash

GAME_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
source "$GAME_DIR/lib/typewriter-regular.sh"

typewriter ""
typewriter "    Thunder roared again outside, heavy rain beat down on the"
typewriter "    large windows that filled the. . . empty Main Hall."
typewriter ""
typewriter "        Barry: Wesker! Help me look for him, Jill."
typewriter ""
typewriter "    . . . . ."
typewriter ""
typewriter "        Barry: Find anything, Jill?"
typewriter "        Jill: Nothing. What is this all about? I can't"
typewriter "          figure it out at all."
typewriter "        Barry: Beats me, too."
typewriter "        Jill: Now it's Wesker's time to disappear! I don't"
typewriter "          know what's going on."
typewriter "        Barry: Let's search for him together."
typewriter "           Maybe check the dining room again."      
typewriter ""
